{% set name = "headerparser" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/headerparser-{{ version }}.tar.gz
  sha256: 2e24ae218ed5d2ef5839fafeff084c40ee1e317bbbe6489cfe333385d7cb98e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - attrs >=20.1.0
    - deprecated >=1.2

test:
  imports:
    - headerparser
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/wheelodex/headerparser
  summary: argparse for mail-style headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
